// Package intelligence provides LLM-powered security intelligence generation capabilities
// for the debug agent.
//
// This package analyzes reconnaissance data stored in the knowledge graph to generate
// actionable security intelligence, risk assessments, attack path analysis, and
// remediation recommendations. It leverages LLM completion via the agent harness to
// synthesize findings across multiple reconnaissance phases into coherent security
// assessments.
//
// The intelligence generator queries the knowledge graph for phase-specific or mission-wide
// data, constructs analysis prompts, invokes LLM completion, parses structured responses,
// and stores intelligence nodes back into the knowledge graph with appropriate relationships
// to source entities (hosts, ports, endpoints, findings).
package intelligence

import (
	"context"
	"time"
)

// RiskLevel represents the severity assessment of a security risk.
type RiskLevel string

const (
	// RiskCritical indicates immediate exploitation risk requiring urgent remediation.
	RiskCritical RiskLevel = "critical"

	// RiskHigh indicates significant security risk requiring prompt attention.
	RiskHigh RiskLevel = "high"

	// RiskMedium indicates moderate security risk requiring planned remediation.
	RiskMedium RiskLevel = "medium"

	// RiskLow indicates minor security concern with lower priority remediation.
	RiskLow RiskLevel = "low"

	// RiskInfo indicates informational finding with no immediate security impact.
	RiskInfo RiskLevel = "info"
)

// Priority represents the urgency level for implementing recommendations.
type Priority string

const (
	// PriorityImmediate indicates recommendations requiring immediate action (hours to days).
	PriorityImmediate Priority = "immediate"

	// PriorityShortTerm indicates recommendations for short-term implementation (weeks).
	PriorityShortTerm Priority = "short-term"

	// PriorityLongTerm indicates recommendations for long-term strategic improvements (months).
	PriorityLongTerm Priority = "long-term"
)

// IntelligenceGenerator defines the interface for generating LLM-powered security intelligence
// from reconnaissance data stored in the knowledge graph. Implementations query GraphRAG for
// phase-specific or mission-wide entities, generate analysis prompts, invoke LLM completion,
// parse structured responses, and store intelligence nodes with relationships to source data.
type IntelligenceGenerator interface {
	// GenerateForPhase generates security intelligence for a specific reconnaissance phase.
	// This method analyzes phase-specific entities in the knowledge graph (hosts, ports,
	// endpoints, technologies, findings) to produce focused intelligence about that phase's
	// discoveries.
	//
	// The phase parameter specifies which reconnaissance phase to analyze (discover, probe,
	// scan, domain). The missionID parameter identifies the mission context for GraphRAG queries.
	//
	// Returns an Intelligence struct containing the LLM-generated analysis including summary,
	// risk assessment, attack paths, and recommendations specific to that phase. The intelligence
	// is also stored as a node in the knowledge graph with ANALYZES relationships to source
	// entities and a GENERATED_BY relationship to the LLM call node.
	//
	// The implementation uses:
	// - agent.Harness.GraphRAGQuery() to retrieve phase entities
	// - agent.Harness.Complete() to generate intelligence via LLM
	// - agent.Harness.GraphRAGStore() to persist intelligence node
	//
	// LLM failures return an error; the intelligence node is not created on failure.
	GenerateForPhase(ctx context.Context, missionID string, phase string) (*Intelligence, error)

	// GenerateSummary generates mission-wide security intelligence synthesizing findings
	// across all reconnaissance phases. This method analyzes the complete knowledge graph
	// for a mission to produce comprehensive intelligence covering the entire attack surface.
	//
	// The missionID parameter identifies the mission context for GraphRAG queries.
	//
	// Returns an Intelligence struct containing the LLM-generated mission summary including
	// overall risk assessment, complete attack path analysis across all phases, prioritized
	// recommendations, and confidence scoring. The intelligence is stored as a summary node
	// in the knowledge graph.
	//
	// This is typically called after all reconnaissance phases complete to provide a
	// holistic security assessment.
	//
	// The implementation follows the same pattern as GenerateForPhase but queries all
	// phase entities and uses a summary-focused prompt template.
	GenerateSummary(ctx context.Context, missionID string) (*Intelligence, error)
}

// Intelligence represents structured security intelligence generated by LLM analysis of
// reconnaissance data. This structure contains actionable insights, risk assessments,
// attack paths, and remediation recommendations derived from knowledge graph entities.
type Intelligence struct {
	// MissionID identifies the mission context this intelligence was generated for.
	MissionID string

	// Phase identifies the reconnaissance phase this intelligence analyzes.
	// Empty string for mission-wide summary intelligence.
	Phase string

	// Summary provides an executive summary of the security findings and key insights.
	// This is a concise (2-4 paragraph) overview suitable for security leadership.
	Summary string

	// RiskAssessment provides an overall risk evaluation including severity, likelihood,
	// and potential business impact. This synthesizes findings into an actionable risk posture.
	RiskAssessment string

	// AttackPaths contains identified attack scenarios that adversaries could exploit.
	// Each path describes a sequence of exploitation steps from initial access to impact.
	AttackPaths []AttackPath

	// Recommendations contains prioritized remediation actions to reduce identified risks.
	// Recommendations are ordered by priority (immediate, short-term, long-term).
	Recommendations []Recommendation

	// Confidence is a score (0.0 to 1.0) indicating the LLM's confidence in this analysis.
	// Higher values indicate stronger evidence and more deterministic conclusions.
	// Lower values indicate ambiguous data or speculative analysis requiring validation.
	Confidence float64

	// SourceNodeCount is the number of knowledge graph nodes analyzed to generate this intelligence.
	// This provides insight into the data volume supporting the analysis.
	SourceNodeCount int

	// SourceLLMCallID is the identifier of the LLM call node that generated this intelligence.
	// This enables audit trail and reproducibility through the GENERATED_BY relationship.
	SourceLLMCallID string

	// Model identifies the LLM model used for generation (e.g., "claude-opus-4", "gpt-4").
	Model string

	// Timestamp records when this intelligence was generated.
	Timestamp time.Time
}

// AttackPath represents a sequence of exploitation steps that an adversary could follow
// to compromise the target environment. Attack paths synthesize multiple findings into
// coherent attack scenarios, helping defenders prioritize remediation based on realistic
// threat progression.
type AttackPath struct {
	// Name is a short descriptive title for this attack path (e.g., "Unauthenticated RCE via SSRF").
	Name string

	// Description provides a detailed explanation of the attack scenario including
	// initial access, privilege escalation, lateral movement, and potential impact.
	Description string

	// Steps contains the ordered sequence of actions an adversary would take to execute this attack.
	// Each step describes the technique, required access, and outcome.
	Steps []string

	// Risk indicates the overall risk level of this attack path based on exploitability,
	// likelihood, and potential impact.
	Risk RiskLevel

	// FindingIDs contains the knowledge graph IDs of finding nodes that contribute to this attack path.
	// This links the attack path back to specific reconnaissance findings.
	FindingIDs []string
}

// Recommendation represents a prioritized remediation action to address identified security risks.
// Recommendations are actionable, specific, and ordered by priority to guide security response.
type Recommendation struct {
	// Title is a short descriptive summary of the recommended action
	// (e.g., "Patch Apache Struts to version 2.5.30+").
	Title string

	// Description provides detailed guidance on implementing this recommendation including
	// specific steps, configuration changes, or compensating controls.
	Description string

	// Priority indicates the urgency of implementing this recommendation based on risk
	// and exploitability.
	Priority Priority

	// AffectedNodeIDs contains the knowledge graph IDs of nodes (hosts, endpoints, findings)
	// that this recommendation addresses. This enables targeted remediation tracking.
	AffectedNodeIDs []string
}
